/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprueba;

/**
 *
 * @author Andrea Palomo
 */
public class EliminarEstampas extends javax.swing.JFrame {

    /**
     * Creates new form EliminarEstampas
     */
    public EliminarEstampas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrej = new javax.swing.JTextField();
        rutaimage = new javax.swing.JTextField();
        equiponom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        equiponom1 = new javax.swing.JTextField();
        rareza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea Palomo\\Documents\\NetBeansProjects\\ProyectoPrueba\\panini.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de jugador:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 94, 168, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de equipo:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 139, 154, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ruta de imagen:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 221, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rareza");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 180, -1, -1));

        nombrej.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombrej.setToolTipText("");
        nombrej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrejActionPerformed(evt);
            }
        });
        getContentPane().add(nombrej, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 93, 190, -1));

        rutaimage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rutaimage.setToolTipText("");
        rutaimage.setEnabled(false);
        getContentPane().add(rutaimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 220, 190, -1));

        equiponom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        equiponom.setToolTipText("");
        equiponom.setEnabled(false);
        equiponom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiponomActionPerformed(evt);
            }
        });
        getContentPane().add(equiponom, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 136, 190, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Eliminar estampas");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 226, -1));

        Eliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 279, 131, -1));

        Regresar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 279, 155, -1));

        Buscar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 89, -1, -1));

        equiponom1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        equiponom1.setToolTipText("");
        equiponom1.setEnabled(false);
        equiponom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiponom1ActionPerformed(evt);
            }
        });
        getContentPane().add(equiponom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 136, 190, -1));

        rareza.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rareza.setEnabled(false);
        getContentPane().add(rareza, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea Palomo\\Documents\\NetBeansProjects\\ProyectoPrueba\\panini.jpg")); // NOI18N
        jLabel7.setText("jLabel5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 710, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrejActionPerformed

    private void equiponomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiponomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equiponomActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        String nombredelj, nombredele, raro,rutadeimagen;
        nombredelj= nombrej.getText();
        nombredele= equiponom.getText();
        rutadeimagen = rutaimage.getText();
        int rarocombo = 0;
        rarocombo =Integer.parseInt(rareza.getText());

        RegistroEstampas.listitaestampas.eliminar(nombredelj, nombredele, rarocombo, rutadeimagen);
        RegistroEstampas.listitaestampas.mostrar();
        nombrej.setText(null);
        equiponom.setText(null);
        rutaimage.setText(null);
        rareza.getText();
    }//GEN-LAST:event_EliminarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:}
        FrameAdministrador obj = new FrameAdministrador();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String nombredelj, nombredele, raro,rutadeimagen;
        nombredelj= nombrej.getText();
        nombredele= equiponom.getText();
        rutadeimagen = rutaimage.getText();
        int rarocombo = 0;
        raro =rareza.getText();

        RegistroEstampas.listitaestampas.buscar(nombredelj, nombredele, rarocombo, rutadeimagen);
        RegistroEstampas.listitaestampas.mostrar();
        nombrej.setText(ListaEstampas.nj);
        equiponom.setText(ListaEstampas.ne);
        rutaimage.setText(ListaEstampas.rutas);
        rareza.setText(String.valueOf(ListaEstampas.raros));
    }//GEN-LAST:event_BuscarActionPerformed

    private void equiponom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiponom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equiponom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarEstampas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarEstampas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarEstampas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarEstampas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarEstampas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField equiponom;
    private javax.swing.JTextField equiponom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombrej;
    private javax.swing.JTextField rareza;
    private javax.swing.JTextField rutaimage;
    // End of variables declaration//GEN-END:variables
}
