/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprueba;

/**
 *
 * @author Andrea Palomo
 */
public class FrameAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdministrador
     */
    public FrameAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        crearj = new javax.swing.JButton();
        editarj = new javax.swing.JButton();
        eliminarj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crearequi = new javax.swing.JButton();
        editarequi = new javax.swing.JButton();
        eliminarequi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        archequ = new javax.swing.JButton();
        archjugadores = new javax.swing.JButton();
        archestampas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setText("CRUD de Usuarios");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("CRUD de Jugadores");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Carga Masiva");

        crear.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        crearj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crearj.setText("Crear");
        crearj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearjActionPerformed(evt);
            }
        });

        editarj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editarj.setText("Editar");
        editarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjActionPerformed(evt);
            }
        });

        eliminarj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminarj.setText("Eliminar");
        eliminarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("CRUD de Equipos");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("CRUD de Estampas");

        crearequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crearequi.setText("Crear");
        crearequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearequiActionPerformed(evt);
            }
        });

        editarequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editarequi.setText("Editar");
        editarequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarequiActionPerformed(evt);
            }
        });

        eliminarequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminarequi.setText("Eliminar");
        eliminarequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarequiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton1.setText("jButton1");

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton2.setText("jButton2");

        jButton3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton3.setText("jButton3");

        archequ.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archequ.setText("Archivo de equipos");

        archjugadores.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archjugadores.setText("Archivo de jugadores");

        archestampas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archestampas.setText("Archivo de estampas");
        archestampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archestampasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADMINISTRADOR");

        Salir.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Salir.setText("LogOut");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(Salir)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(archequ)
                                .addGap(18, 18, 18)
                                .addComponent(archjugadores))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(archestampas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crearequi)
                                .addGap(18, 18, 18)
                                .addComponent(editarequi)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarequi))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crear)
                                .addGap(18, 18, 18)
                                .addComponent(editar)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crearj)
                                .addGap(18, 18, 18)
                                .addComponent(editarj)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarj))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(editar)
                    .addComponent(eliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearj)
                    .addComponent(editarj)
                    .addComponent(eliminarj))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearequi)
                    .addComponent(editarequi)
                    .addComponent(eliminarequi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archequ)
                    .addComponent(archjugadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archestampas)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjActionPerformed
        // TODO add your handling code here:
        EliminaJugadores obj= new EliminaJugadores();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_eliminarjActionPerformed

    private void archestampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archestampasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archestampasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        Login obj= new Login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        RegistroU obj= new RegistroU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        EditaU obj= new EditaU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        EliminaU obj= new EliminaU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_eliminarActionPerformed

    private void crearjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearjActionPerformed
        // TODO add your handling code here:
        Registrosjugadores obj= new Registrosjugadores();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearjActionPerformed

    private void editarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjActionPerformed
        // TODO add your handling code here:
        EditaJugadores obj= new EditaJugadores();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarjActionPerformed

    private void crearequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearequiActionPerformed
        // TODO add your handling code here:
        RegistroEquipos obj = new RegistroEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearequiActionPerformed

    private void editarequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarequiActionPerformed
        // TODO add your handling code here:
        EditaEquipos obj = new EditaEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarequiActionPerformed

    private void eliminarequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarequiActionPerformed
        // TODO add your handling code here:
        EliminaEquipos obj = new EliminaEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_eliminarequiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton archequ;
    private javax.swing.JButton archestampas;
    private javax.swing.JButton archjugadores;
    private javax.swing.JButton crear;
    private javax.swing.JButton crearequi;
    private javax.swing.JButton crearj;
    private javax.swing.JButton editar;
    private javax.swing.JButton editarequi;
    private javax.swing.JButton editarj;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminarequi;
    private javax.swing.JButton eliminarj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
