/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprueba;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea Palomo
 */
public class FrameAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdministrador
     */
    public FrameAdministrador() {
        initComponents();
        setTitle("ADMINISTRADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        crearj = new javax.swing.JButton();
        editarj = new javax.swing.JButton();
        eliminarj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crearequi = new javax.swing.JButton();
        editarequi = new javax.swing.JButton();
        eliminarequi = new javax.swing.JButton();
        Crearestampas = new javax.swing.JButton();
        EditarEstampas = new javax.swing.JButton();
        EliminarEstampas = new javax.swing.JButton();
        archequ = new javax.swing.JButton();
        archjugadores = new javax.swing.JButton();
        archestampas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CRUD de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 55, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRUD de Jugadores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 126, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carga Masiva");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 317, -1, -1));

        crear.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 85, -1, -1));

        editar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 85, -1, -1));

        eliminar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 85, -1, -1));

        crearj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crearj.setText("Crear");
        crearj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearjActionPerformed(evt);
            }
        });
        getContentPane().add(crearj, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 151, -1, -1));

        editarj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editarj.setText("Editar");
        editarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjActionPerformed(evt);
            }
        });
        getContentPane().add(editarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 151, -1, -1));

        eliminarj.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminarj.setText("Eliminar");
        eliminarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 151, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CRUD de Equipos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 192, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CRUD de Estampas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 251, -1, -1));

        crearequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        crearequi.setText("Crear");
        crearequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearequiActionPerformed(evt);
            }
        });
        getContentPane().add(crearequi, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 222, -1, -1));

        editarequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editarequi.setText("Editar");
        editarequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarequiActionPerformed(evt);
            }
        });
        getContentPane().add(editarequi, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 222, -1, -1));

        eliminarequi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eliminarequi.setText("Eliminar");
        eliminarequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarequiActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarequi, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 222, -1, -1));

        Crearestampas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Crearestampas.setText("Crear");
        Crearestampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearestampasActionPerformed(evt);
            }
        });
        getContentPane().add(Crearestampas, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 276, -1, -1));

        EditarEstampas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        EditarEstampas.setText("Editar");
        EditarEstampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEstampasActionPerformed(evt);
            }
        });
        getContentPane().add(EditarEstampas, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 276, -1, -1));

        EliminarEstampas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        EliminarEstampas.setText("Eliminar");
        EliminarEstampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstampasActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarEstampas, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 276, -1, -1));

        archequ.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archequ.setText("Archivo de equipos");
        archequ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archequActionPerformed(evt);
            }
        });
        getContentPane().add(archequ, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 346, -1, -1));

        archjugadores.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archjugadores.setText("Archivo de jugadores");
        archjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archjugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(archjugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 346, -1, -1));

        archestampas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        archestampas.setText("Archivo de estampas");
        archestampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archestampasActionPerformed(evt);
            }
        });
        getContentPane().add(archestampas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADMINISTRADOR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 20, 151, -1));

        Salir.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Salir.setText("LogOut");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 21, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea Palomo\\Documents\\NetBeansProjects\\ProyectoPrueba\\azulpanini.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -10, 790, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjActionPerformed
        // TODO add your handling code here:
        EliminaJugadores obj = new EliminaJugadores();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_eliminarjActionPerformed

    private void archestampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archestampasActionPerformed
        // TODO add your handling code here:
        ArchivoEstampas archivoes = new ArchivoEstampas();
        try {
            archivoes.mostrar();
        } catch (IOException ex) {
            Logger.getLogger(FrameAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        RegistroEstampas.listitaestampas.mostrar();
        JOptionPane.showMessageDialog(null, "SE HA AGREGADO UNA LISTA DE ESTAMPAS", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                                                 
    }//GEN-LAST:event_archestampasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        Login obj = new Login();
        obj.setVisible(true);
        dispose();
//        VerEstampas obj = new VerEstampas();
//        obj.setVisible(true);
        
    }//GEN-LAST:event_SalirActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        RegistroU obj = new RegistroU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        EditaU obj = new EditaU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        EliminaU obj = new EliminaU();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_eliminarActionPerformed

    private void crearjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearjActionPerformed
        // TODO add your handling code here:
        Registrosjugadores obj = new Registrosjugadores();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearjActionPerformed

    private void editarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjActionPerformed
        // TODO add your handling code here:
        EditaJugadores obj = new EditaJugadores();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarjActionPerformed

    private void crearequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearequiActionPerformed
        // TODO add your handling code here:
        RegistroEquipos obj = new RegistroEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearequiActionPerformed

    private void editarequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarequiActionPerformed
        // TODO add your handling code here:
        EditaEquipos obj = new EditaEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarequiActionPerformed

    private void eliminarequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarequiActionPerformed
        // TODO add your handling code here:
        EliminaEquipos obj = new EliminaEquipos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_eliminarequiActionPerformed

    private void archequActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archequActionPerformed
        // TODO add your handling code here:\
        ArchivoEquipos archivoe = new ArchivoEquipos();
        try {
            archivoe.mostrar();
        } catch (IOException ex) {
            Logger.getLogger(FrameAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        RegistroEquipos.listitaequipos.mostrar();
        JOptionPane.showMessageDialog(null, "SE HA AGREGADO UNA LISTA DE EQUIPOS", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_archequActionPerformed

    private void archjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archjugadoresActionPerformed
        // TODO add your handling code here:
        ArchivoJugadores archivoj = new ArchivoJugadores();
        try {
            archivoj.mostrar();
        } catch (IOException ex) {
            Logger.getLogger(FrameAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        Registrosjugadores.listitajugadores.mostrar();
        JOptionPane.showMessageDialog(null, "SE HA AGREGADO UNA LISTA DE JUGADORES", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_archjugadoresActionPerformed

    private void CrearestampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearestampasActionPerformed
        // TODO add your handling code here:
        RegistroEstampas obj=new RegistroEstampas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_CrearestampasActionPerformed

    private void EditarEstampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEstampasActionPerformed
        // TODO add your handling code here:
        EditaEstampas obj=new EditaEstampas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_EditarEstampasActionPerformed

    private void EliminarEstampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstampasActionPerformed
        // TODO add your handling code here:
//        EliminarEstampas obj=new EliminarEstampas();
        EliminarEstampas obj=new EliminarEstampas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarEstampasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crearestampas;
    private javax.swing.JButton EditarEstampas;
    private javax.swing.JButton EliminarEstampas;
    private javax.swing.JButton Salir;
    private javax.swing.JButton archequ;
    private javax.swing.JButton archestampas;
    private javax.swing.JButton archjugadores;
    private javax.swing.JButton crear;
    private javax.swing.JButton crearequi;
    private javax.swing.JButton crearj;
    private javax.swing.JButton editar;
    private javax.swing.JButton editarequi;
    private javax.swing.JButton editarj;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminarequi;
    private javax.swing.JButton eliminarj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
