/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprueba;

/**
 *
 * @author Andrea Palomo
 */
public class Registrosjugadores extends javax.swing.JFrame {

    public static ListaJugadores listitajugadores = new ListaJugadores();

    /**
     * Creates new form Registrosjugadores
     */
    public Registrosjugadores() {
        initComponents();
        setTitle("REGISTRO DE JUGADORES");
        RegistroEquipos.listitaequipos.itemsdeequipos(idequipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        nombrej = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        idequipo = new javax.swing.JComboBox<>();
        nocamisola = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        titular = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        posicion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Equipo:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 230, -1, -1));

        nombrej.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombrej.setToolTipText("");
        getContentPane().add(nombrej, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 79, 216, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRO DE JUGADORES");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        Registrarse.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 268, -1, -1));

        idequipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idequipoActionPerformed(evt);
            }
        });
        getContentPane().add(idequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 227, 216, -1));

        nocamisola.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nocamisola.setToolTipText("");
        getContentPane().add(nocamisola, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 113, 216, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Camisola:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 118, -1, -1));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 87, -1, -1));

        Regresar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 268, -1, -1));

        titular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titular", "Banca" }));
        titular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titularActionPerformed(evt);
            }
        });
        getContentPane().add(titular, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 187, 216, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Titular o Banca:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 188, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Posición:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        posicion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 147, 216, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea Palomo\\Documents\\NetBeansProjects\\ProyectoPrueba\\panini.jpg")); // NOI18N
        jLabel7.setText("jLabel5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 670, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titularActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_titularActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        FrameAdministrador obj = new FrameAdministrador();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        // TODO add your handling code here:
        String nombrejs, numcamisola, posicionc, titularobanca, titularob = null;
        nombrejs = nombrej.getText();
        numcamisola = nocamisola.getText();
        posicionc = posicion.getText();;
        
        String valorComboBox = "";
        valorComboBox = titular.getSelectedItem().toString();
        if ("Titular".equals(valorComboBox)) {
            titularob = "titular";
//            System.out.println(titularob);
        } else if ("Banca".equals(valorComboBox)) {
            titularob = "banca";
//            System.out.println(titularob);
        }
        String idequipos = (String) idequipo.getSelectedItem();
//        System.out.println(idequipos);
        
        listitajugadores.insertarinicio(nombrejs, numcamisola, posicionc, titularob, idequipos);
        listitajugadores.mostrar();
        RegistroEquipos.listitaequipos.buscarsiexistenlistas(idequipos);
        
        nombrej.setText(null);
        nocamisola.setText(null);
        posicion.setText(null);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void idequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idequipoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_idequipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrosjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrosjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrosjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrosjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrosjugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton Regresar;
    private javax.swing.JComboBox<String> idequipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nocamisola;
    private javax.swing.JTextField nombrej;
    private javax.swing.JTextField posicion;
    private javax.swing.JComboBox<String> titular;
    // End of variables declaration//GEN-END:variables
}
